### ISSUE TITLE
Support sf as the input for the parameter vect?

### ISSUE THREAD

**Issue by LLeiSong** [adamlilith/fasterRaster#17]
Hi Adam, this is a great package to make the work related to rasterize and distance much faster in R. Thanks a lot. I realized now it only support `sp` spatial features (I am sorry if I am wrong about this). It would be helpful if the package could support the new `sf` simple features so we don't have to switch back and forth.

**Comment by adamlilith** [comment]
Hi LLeiSong, thank you for the positive feedback! This is a good idea, but I *believe* it would be no faster than converting `sf` objects to `sp`  objects outside of the functions.  Shapefiles and rasters are sent to GRASS via the `writeVECT` and `writeRAST` functions, which take as arguments `sp` objects and `rasters`, respectively.  So one must first convert an `sf` object to an `sp` object anyway.

**Comment by LLeiSong** [comment]
Hi Adam, thanks very much for the explanation. It makes perfect sense. I will close the comment. Thanks also for the link to the new package. It is definitely worth to use.
