### ISSUE TITLE
Can't install enmSdm because grpregOverlap is gone

### ISSUE THREAD

**Issue by tinsman** [adamlilith/fasterRaster#18]
Hi Adam,

I can't install enmSdm or fasterRaster, because I get this error: `ERROR: dependency 'grpregOverlap' is not available for package 'enmSdm'` because grpregOverlap has been removed from CRAN.

Is there a workaround?

Thanks!
Jen

**Comment by adamlilith** [comment]
Hi Jen,

This is an error from the package enmSdm (which fasterRaster depends on).  It seems no one is maintaining grpregOverlap, so it hasn't been recompiled for newer versions of R. However, you can download an older version and install it manually from the tar file (https://cran.r-project.org/web/packages/grpregOverlap/index.html ... see the "archive" link).  I do not recall exactly, but I think you may need to do this for the "grpreg" package, too, which grpregOverlap depends on.

By the way, you might also look at the terra package (on CRAN and GH), which is the successor to the raster package.  It's written almost entirely in C so runs much faster than raster functions. However, it's still somewhat in development, but if it works, it will in most cases be faster and easier to use than fasterRaster.

Best,
Adam

**Comment by tinsman** [comment]
Hi Adam,

This is so helpful! Thank you for this, and for the packages you've written.

Jen
