### ISSUE TITLE
Error message  in rgrass7::initGRASS

### ISSUE THREAD

**Issue by IlhemB** [adamlilith/fasterRaster#23]
Hi Adam, 

First of all, I want to thank you for this really helpful package. I had an error while I was trying to use the function "fasterVectToRastDistance". Here the error message : 

  Error in rgrass7::initGRASS(gisBase = grassDir, home = tempDir, location = location,  : 
  /Users/ilhem/grassdata does not contain bin, the directory with GRASS programs

Is it possible to resolve this error? 
Thank you in advance 
Ilhem

**Comment by adamlilith** [comment]
Hi Illhem,

Thanks for your message.  The error you are receiving is coming from the initGRASS function in the rgrass7 package, so if it's an error in that function you should contact Roger Bivand, the manager of rgrass7.  However, your error message makes me think that function is working as it should.

What is the string you're using for grassDir? It looks to me like you're pointing it to "/Users/ilhem/grassdata" which probably isn't where GRASS is installed.  On my system (Windows 7) it's at 'C:/Program Files/GRASS GIS 7.8'.

Adam

**Comment by IlhemB** [comment]
Ok, thank you very much. 
Best regards 
Ilhem

**Comment by Otoliths** [comment]
> Hi Adam,
> 
> First of all, I want to thank you for this really helpful package. I had an error while I was trying to use the function "fasterVectToRastDistance". Here the error message :
> 
> Error in rgrass7::initGRASS(gisBase = grassDir, home = tempDir, location = location, :
> /Users/ilhem/grassdata does not contain bin, the directory with GRASS programs
> 
> Is it possible to resolve this error?
> Thank you in advance
> Ilhem

Hi Illhem,

I solved the problem on my system (MacOS) it's at '/Applications/GRASS-7.8.app/Contents/Resources'., which may help you.

>library(fasterRaster)
>data(madForest2000)
>data(madRivers)
>grassDir <- "/Applications/GRASS-7.8.app/Contents/Resources"
>distToRiver <- fasterVectToRastDistance(rast=madForest2000,
                                        vect=madRivers,
                                        grassDir = grassDir)
>plot(distToRiver, main='Distance to Rivers (m)')
>plot(madRivers, col='blue', add=TRUE)

>sessioninfo::platform_info()
 # setting  value                       
# version  R version 4.0.5 (2021-03-31)
# os       macOS Big Sur 10.16         
# system   x86_64, darwin17.0          
# ui       RStudio                     
# language (EN)                        
# collate  en_US.UTF-8                 
# ctype    en_US.UTF-8                 
# tz       Asia/Shanghai               
# date     2021-06-02
