### ISSUE TITLE
fasterFragmentation returns more values than input

### ISSUE THREAD

**Issue by lukasbaumbach** [adamlilith/fasterRaster#25]
Hi,

first of all thanks for creating the `fasterFragmentation` function, it is very handy and runs extremely fast!
When checking the output, however, I discovered that the rasters had significantly more "filled" values (non-NA/non-zero) than my input raster (with the madForest2000 example data it was original: 842'726; output$class: 1'131'486).
I suspect this is due to the windows being used, so that values are returned for the whole window instead of just the window center.
This leads to the undesirable result, that cells that had not been forest before are suddenly shown as "edge" or similar and also area statistics do not add up anymore when compared to the original raster.

As a quick hack I just masked the fragmentation output with the input raster, however I'm not sure, if all cells have correct classes now since I cut away the "edges".

Best,
Lukas

**Comment by adamlilith** [comment]
Hi Lukas,

Thank you for the kind message.  I think the results you are finding sound reasonable.  The fragmentation index calculates, for a focal cell, the degree of connectivity, density, and from these fragmentation in the surrounding area (3x3 cells by default). So even if a cell has no forest (is NA), it can get assigned a value based on whether or not there is any forest in the region.  Cells that do have forest will also get assigned a value.  So the total number of non-NA cells should be larger in the output than in the input.

It's hard to see this unless you zoom in on a raster.  I'll paste in a zoomed version of the example so you can see how cells are "added" around the border of forest cells. Here, I'm zooming in on a particular fragment (bottom row).

![frag](https://user-images.githubusercontent.com/7577062/111486947-ed415480-8705-11eb-96fd-fb2e22b67329.jpeg)

In addition, the can function add "padding" rows/columns around the raster to help account for the fact that the calculation is done using a moving window. If padding is not done, then cells at the edge can have their windows cropped.  Padding is not done by default (pad = FALSE), but it can be turned on.  Using padding can also increase the number of non-NA cells, as well as the total number of cells in the raster.

Hope that helps!
Adam

**Comment by lukasbaumbach** [comment]
Hi Adam,

thanks for the quick reponse and detailed explanation! As I see it, the benefit of assigning values to non-forest cells within the moving windows depends on the goal of the analysis and definition of classes. For buffer and transition analysis around protected areas this behaviour is probably well-suited. In my case, however, I am mainly interested in area statistics about how many forest cells fall into which class. Since I have several forest types in my original data set and pick them out one at a time as binary maps to compute fragmentation, the "non-forest-padding" leads to area overlaps. Finally - this may be subjective - but to my understanding I would rather classify a forest cell bordering non-forest as "edge" (or similar), than the non-forest cell next to it.

So do you think it might be an option to include an argument (like an inverse `pad` argument) to only allow value assignment to forest cells? This would be really cool!

Cheers,
Lukas

**Comment by adamlilith** [comment]
Hi Lukas,

I see how what you're describing could be a problem.  You could do what you suggest by multiplying the forest raster for each type of forest (which I assume is all 1/0 or 1/NA values) by the fragmentation raster that fasterFragmentation produces. This way, you will only have cells with forest classified.

I think the one potential problem is if you have different types of forest that are immediately adjacent to one another.  If you provide fasterFragmentation a raster for a particular forest type that's adjacent to another forest type (cells are touching or within the 3x3 neighborhood), then fasterFragmentation will indicate that the first forest might be more fragmented than it is because it can't "see" the other forest types. But maybe that's OK for your analysis...?

Adam

**Comment by lukasbaumbach** [comment]
Okay, this is more or less what I figured. I just want to make sure, that the classification results for a forest cell do not change depending on whether I allow non-forest cells to have class values or not. Could you maybe briefly explain how the assignment happens? I was imagining the function to loop through forest cells only (get the window, return a class value), but how does the assignment for non-forest cells work then?

I see that one has to be cautious with adjacent forest types, but I guess this is more of an interpretation/result communication challenge.

Best

**Comment by adamlilith** [comment]
Hi Lukas,

The procedure examines each cell (forest or not) and its surrounding cells (3x3 by default), then calculates the density and connectivity across that window.  It then assigns values to the focal cell for density and connectivity, and from there the fragmentation index.  I suggest reading reading the paper it's based on, especially if you're using the fragmentation index in a project:

Riitters, K., J. Wickham, R. O'Neill, B. Jones, and E. Smith. 2000. Global-scale patterns of forest fragmentation. [Conservation Ecology](iitters, K., J. Wickham, R. O'Neill, B. Jones, and E. Smith. 2000. Global-scale patterns of forest fragmentation. Conservation Ecology 4:3. URL: <https://www.jstor.org/stable/26271763>) 4:3.

Also note the [erratum](https://www.ecologyandsociety.org/vol4/iss2/art3/errata/january26.2001.html).

The paper is open-access, so there should be no problem obtaining it.

Adam

**Comment by lukasbaumbach** [comment]
Alright, then I was just incorrectly assuming the window analysis would only be performed for the forest subset instead of the whole input raster. Everything's clear now, thank you for your patient explanation!

Best,
Lukas
