### ISSUE TITLE
Finding the cause of error message in rgrass7::initGRASS on MacOS

### ISSUE THREAD

**Issue by Otoliths** [adamlilith/fasterRaster#26]
Hi Adam,

I solved grassDir on my system (MacOS) it's at '/Applications/GRASS-7.8.app/Contents/Resources'., which may help you. You can add it to the example.

>library(fasterRaster)
>data(madForest2000)
>data(madRivers)
>grassDir <- "/Applications/GRASS-7.8.app/Contents/Resources"
>distToRiver <- fasterVectToRastDistance(rast=madForest2000, vect=madRivers, grassDir = grassDir)
>plot(distToRiver, main='Distance to Rivers (m)')
>plot(madRivers, col='blue', add=TRUE)

sessioninfo::platform_info()
```
setting  value                       
version  R version 4.0.5 (2021-03-31)
os       macOS Big Sur 10.16         
system   x86_64, darwin17.0          
ui       RStudio                     
language (EN)                        
collate  en_US.UTF-8                 
ctype    en_US.UTF-8                 
tz       Asia/Shanghai               
date     2021-06-02          
```

**Comment by adamlilith** [comment]
Hi Liuyong,

Thank you for letting me know—I actually don’t have access to a Mac, so it is useful for someone else to fix issues like these.

Thanks again,
Adam

From: Liuyong Ding ***@***.***>
Sent: Wednesday, June 2, 2021 1:35 AM
To: adamlilith/fasterRaster ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamlilith/fasterRaster] Finding the cause of error message in rgrass7::initGRASS on MacOS (#26)


Hi Adam,

I solved grassDir on my system (MacOS) it's at '/Applications/GRASS-7.8.app/Contents/Resources'., which may help you. You can add it to the example.

library(fasterRaster)
data(madForest2000)
data(madRivers)
grassDir <- "/Applications/GRASS-7.8.app/Contents/Resources"
distToRiver <- fasterVectToRastDistance(rast=madForest2000, vect=madRivers, grassDir = grassDir)
plot(distToRiver, main='Distance to Rivers (m)')
plot(madRivers, col='blue', add=TRUE)

sessioninfo::platform_info()

setting  value

version  R version 4.0.5 (2021-03-31)

os       macOS Big Sur 10.16

system   x86_64, darwin17.0

ui       RStudio

language (EN)

collate  en_US.UTF-8

ctype    en_US.UTF-8

tz       Asia/Shanghai

date     2021-06-02
