### ISSUE TITLE
Handling of rasterBrick or RasterStacks?

### ISSUE THREAD

**Issue by martindoublem** [adamlilith/fasterRaster#28]
I was hoping to use your package to handle raterbrick or rasterStacks.

Is there anyway this could be implemented?

Tried using a rasterBrick on the function fasterRasterProject as input and the output was a single rasterlayer.

Looking at the code, it seems that the output is a raster so this would obviously have to be changed, however the input into grass seems to go as a spatialgridDataframe, do you happen to know if those can handle bricks?

**Comment by adamlilith** [comment]
Hi Martin,

I am sorry, I have only tested it with single rasters. I would suggest using the terra package (the successor to the raster package). The terra package is much faster. The relevant function there is project().

Good luck,
Adam

Adam B. Smith, Ph.D.

Associate Scientist in Global Change

Center for Conservation and Sustainable Development

Missouri Botanical Garden

Saint Louis, Missouri USA

www.earthSkySea.org



________________________________
From: Martin Morlot ***@***.***>
Sent: Wednesday, July 7, 2021 11:13:40 AM
To: adamlilith/fasterRaster ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamlilith/fasterRaster] Handling of rasterBrick or RasterStacks? (#28)


I was hoping to use your package to handle raterbrick or rasterStacks.

Is there anyway this could be implemented.

Tried using a rasterBrick on the function fasterRasterProject as input and the output was a single rasterlayer?

Looking at the code, it seems that the output is a raster, however the input into grass seems to go as a spatialgridDataframe, do you happen to know if those can handle Bricks?

**Comment by martindoublem** [comment]
Ok Thank you. Closing this now.
