### ISSUE TITLE
Error in fasterHorizon when grassToR = TRUE

### ISSUE THREAD

**Issue by foresthayes** [adamlilith/fasterRaster#31]
Hi Adam,

The output name in GRASS is incorrectly generated within `fasterHorizon` when `grassToR = TRUE` based on the vector of directions.

https://github.com/adamlilith/fasterRaster/blob/5698316396248b6d4fec4b877db7a7109a4ee7c6/R/fasterHorizon.r#L67-L68

For example, when `direction = 0`, the name provided to` rgrass7::readRAST()` is `c(“horizonHeight_0”, “horizonHeight_0”, “horizonHeight_0”)` instead of `“horizonHeight_000”`.

This issue is fixed by adding the argument `collapse = “”`:

`degs <- paste0(c(ifelse(direction < 100, "0", ""), ifelse(direction < 10, "0", ""), direction), collapse = "")`

Writing this also made me realize that an error would occur if non-integer values are provided for direction (e.g. 90.5). This could be avoided by using `floor()` as GRASS appears to round down to the closest full degree when naming the output. One possible solution:

`degs <- sprintf("%03d", floor(direction))`  

Best,
Forest

**Comment by adamlilith** [comment]
Hi Forest,

Thank you for bringing this to my attention!  Also, thank you for finding the fix!  I have updated the code as per your recommendation.  I also now include a check to see if `directions` is an integer, and if not, round down and make a warning.  The help has been updated accordingly. The new version (0.6.6) is now pulled and merged, and should be available.

Thanks again!
Adam
