### ISSUE TITLE
Old code no longer working

### ISSUE THREAD

**Issue by RJGrayEcology** [adamlilith/fasterRaster#44]
I am trying to make a distance raster with the same river shapefile I have used several times in previous years. I tried using GRASS v. 8.3 and rolled back to 7.8 to see if there was any differece.

**This is my code:**
# set working directory to read in shapefile and country boundary
setwd("D:/Vietnam ENV Data/Rivers and streams")
list.files()
water <- readOGR(getwd(), "columbia_iscgm_vietnam_2007_watrcrsl")
setwd("D:/Vietnam ENV Data/Shapefiles/Vietnam outline")
list.files()
country <- readOGR(getwd(), "Vietnam")
proj4string(country) <- CRS("EPSG:4326")

# make an empty raster that matches the extent of your country
r <- raster(x = extent(country), nrows = 2000, ncols = 2000)
r[] <- 1 # set raster value to standard 1 in all cells
# set a latlong projection (this needs to match your shapefiles too)
crs(r) <- "+proj=longlat +datum=WGS84 +no_defs"

# install and open fasterRaster
#Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
#remotes::install_github('adamlilith/fasterRaster', dependencies=TRUE)
library(fasterRaster)
# set GRASS directory
grassDir <- 'C:/Program Files/GRASS GIS 7.8'
distToRiver <- fasterVectToRastDistance(rast=r,
                                        vect=water,
                                        metric="geodesic",
                                        grassDir=grassDir,
                                        meters = TRUE,
                                        )

**This is the run text and errors:**
 
100%
Check if OGR layer <vect> contains polygons...
 100%
WARNING: Vector map <vect> already exists and will be overwritten
Creating attribute table for layer <vect>...
Importing 2397 features (OGR layer <vect>)...
 100%
-----------------------------------------------------
Building topology for vector map <vect@PERMANENT>...
Registering primitives...
Assertion failed: p->count[0] >= p->minfill && p->count[1] >= p->minfill, file split.c, line 591
WARNING: Unable to open vector map <vect@PERMANENT> on level 2. Try to
         rebuild vector topology with v.build.
ERROR: Unable to open vector map <vect>
ERROR: Raster map <vectToRast> not found
ERROR: Raster map <distToVect> not found

**The warnings are as follows:**
Warning messages:
1: Package rgrass7 transitioning to package rgrass for GRASS 7+.
2: Package rgrass7 transitioning to package rgrass for GRASS 7+.
3: Package rgrass7 transitioning to package rgrass for GRASS 7+.
4: Package rgrass7 transitioning to package rgrass for GRASS 7+.
5: Package rgrass7 transitioning to package rgrass for GRASS 7+.
6: Package rgrass7 transitioning to package rgrass for GRASS 7+.
7: Package rgrass7 transitioning to package rgrass for GRASS 7+.
8: In system(syscmd, intern = intern, ignore.stderr = ignore.stderr,  ... :
  running command 'g.proj.exe -w' had status 884
9: Package rgrass7 transitioning to package rgrass for GRASS 7+.
10: Package rgrass7 transitioning to package rgrass for GRASS 7+.
'writeRAST' is deprecated. Use 'write_RAST' instead.
11: Package rgrass7 transitioning to package rgrass for GRASS 7+.
12: Package rgrass7 transitioning to package rgrass for GRASS 7+.
'writeVECT is deprecated. Use 'write_VECT' instead.
13: OGR support is provided by the sf and terra packages among others
14: OGR support is provided by the sf and terra packages among others
15: OGR support is provided by the sf and terra packages among others
16: Package rgrass7 is transitioning to package rgrass for GRASS GIS 7+.
'readRAST' is deprecated. Use 'read_RAST' instead.
17: Package rgrass7 transitioning to package rgrass for GRASS 7+.
18: In system(syscmd, intern = intern, ignore.stderr = ignore.stderr,  ... :
  running command 'g.proj.exe -w' had status 884
19: In system(syscmd, intern = intern, ignore.stderr = ignore.stderr,  ... :
  running command 'r.info.exe -g map=distToVect' had status 1
20: In system(syscmd, intern = intern, ignore.stderr = ignore.stderr,  ... :
  running command 'r.info.exe -r map=distToVect' had status 1
21: In ifelse(x == "NULL", as.numeric(NA), as.numeric(x)) :
  NAs introduced by coercion

**Comment by adamlilith** [comment]
Hi RJGrayEcology,

Sorry this has happened. I've made very few changes to the MAIN branch since it was released 2 years ago, and none to fasterVectToRastDistance(). The issue may be with the `rgrass7` package, which you can see is in a state of transition. Since I didn't write it, I'm not sure I can help with that.

*However*, I am in the middle of writing a more intuitive version of **fasterRaster** for which the `distance()` function works (just tested it today). This new version needs GRASS 8.2 or higher.  Based on what I see above, you can use the new `distance()` function as follows:

(Assume GRASS 8.2+ is installed.)

```{r}
remotes::install_github("adamlilith/fasterRaster@intuitive_fasterRaster", dependencies=TRUE)

library(fasterRaster)
library(sf)
library(terra)

setwd("D:/Vietnam ENV Data/Rivers and streams")

# I'm assuming this is a shapefile:
water <- vect(paste0(getwd(), "/columbia_iscgm_vietnam_2007_watrcrsl.shp"))

# initiate GRASS session in R
grassDir <- "C:/Program Files/GRASS GIS 8.3" # or whatever your version
faster(water, grassDir = grassDir)

# load vectors into GRASS and convert to fasterRaster GVectors
water <- fast(paste0(getwd(), "/columbia_iscgm_vietnam_2007_watrcrsl.shp"))
country <- fast(paste0(getwd(), "/Vietnam.shp"))

# create raster
r <- matrix(NA, nrow = 2000, ncol = 2000)
r <- rast(r, extent = ext(country), crs ="+proj=longlat +datum=WGS84 +no_defs")

# load raster into GRASS and convert to a fasterRaster GRaster
r <- fast(r)

# calculate distance
distToRiver <- distance(r, water, method = "geodesic")

# convert to a SpatRaster (terra package)
distToRiver <- rast(distToRiver)
plot(distToRiver)
```
Please let me know if this doesn't work!
Adam

**Comment by adamlilith** [comment]
PS If you need it as a `raster` package `raster` object, you can simply use `raster(distToRiver)` -- though you may already know that.

**Comment by RJGrayEcology** [comment]
Yeah, using raster was always easiest for me.... But need to start transitioning to terra now :(

Thanks for the updates! I'll test it out today!


--
https://www.svw.vn/
Headquarter       : Cuc Phuong, Nho Quan, Ninh BinhTel                       : (+84) (0) 2293 848 053
Facebook            : Save Vietnam's Wildlife
--------------
Russell J. Gray | Science AdvisorMobile/WA           : (+84) (0) 869 105 617Email                  ***@***.***
 

    On Saturday, July 29, 2023 at 10:45:03 a.m. ICT, Adam B. Smith ***@***.***> wrote:  
 
 


Hi RJGrayEcology,

Sorry this has happened. I've made very few changes to the MAIN branch since it was released 2 years ago, and none to fasterVectToRastDistance(). The issue may be with the rgrass7 package, which you can see is in a state of transition. Since I didn't write it, I'm not sure I can help with that.

However, I am in the middle of writing a more intuitive version of fasterRaster for which the distance() function works (just tested it today). This new version needs GRASS 8.2 or higher. Based on what I see above, you can use the new distance() function as follows:

(Assume GRASS 8.2+ is installed.)
***@***.***_fasterRaster", dependencies=TRUE)

library(fasterRaster)
library(sf)
library(terra)

setwd("D:/Vietnam ENV Data/Rivers and streams")

# I'm assuming this is a shapefile:
water <- vect(paste0(getwd(), "/columbia_iscgm_vietnam_2007_watrcrsl.shp"))

# initiate GRASS session in R
grassDir <- "C:/Program Files/GRASS GIS 8.3" # or whatever your version
faster(water, grassDir = grassDir)

# load vectors into GRASS and convert to fasterRaster GVectors
water <- fast(paste0(getwd(), "/columbia_iscgm_vietnam_2007_watrcrsl.shp"))
country <- fast(paste0(getwd(), "/Vietnam.shp"))

# create raster
r <- matrix(NA, nrow = 2000, ncol = 2000)
r <- rast(r, extent = ext(country), crs ="+proj=longlat +datum=WGS84 +no_defs")

# load raster into GRASS and convert to a fasterRaster GRaster
r <- fast(r)

# calculate distance
distToRiver <- distance(r, water, method = "geodesic")

# convert to a SpatRaster (terra package)
distToRiver <- rast(distToRiver)
plot(distToRiver)

Please let me know if this doesn't work!
Adam
